### ISSUE TITLE
There is a bug occurs when decompress game core with sega mega drive in android chrome

### ISSUE THREAD

**Issue by ajccom** [EmulatorJS/EmulatorJS-netplay-old#48]
I was uploaded a rom named '2020 Nen Super Baseball (Japan).md.zip' at demo page: 'https://demo.emulatorjs.org' in android chrome.

Then I selected game core 'Sega Mega Drive' and click load game button.

After download core, there is a tip at page bottom, "Decompress Game Core 97%".
My problem is the decompress progress always 97% as I tried many times.

I tried in mac chrome, it's ok. But in android chrome, it's not ok.

rom file:
[2020 Nen Super Baseball (Japan).md.zip](https://github.com/EmulatorJS/EmulatorJS-netplay-old/files/13655157/2020.Nen.Super.Baseball.Japan.md.zip)

**Comment by ethanaobrien** [comment]
This is not the right repository
